# Copyright (c) 2022 OpenFaaS Ltd
name: 'hub-mirror'
description: 'Setup local mirror for Docker Hub'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  insecureRegistries:
    description: 'The gateway hostname address or IP address.'
    required: true
    default: "\"192.168.128.1:5000\""
  registryMirrors:
    description: 'Whether to use TLS.'
    required: true
    default: "\"http://192.168.128.1:5000\""
  buildkitRegistryMirror:
    description: 'Registry mirror to be used by buildx builder.'
    required: true
    default: "\"192.168.128.1:5000\""
  buildkitRegistryHTTP:
    description: 'Whether to us HTTP.'
    required: true
    default: "true"
  buildkitRegistryInsecure:
    description: 'Whether to use TLS.'
    required: true
    default: "true"
  
runs:
    using: 'composite'
    steps:
      - name: Setup config
        shell: bash
        id: setup-config
        env:
          INSECURE_REG: ${{ inputs.insecureRegistries }}
          REG_MIRRORS: ${{ inputs.registryMirrors }}
        run: |
           sudo mkdir -p /etc/docker
           cat <<EOF | sudo tee /etc/docker/daemon.json
           {
               "insecure-registries" : [${INSECURE_REG} ],
               "registry-mirrors": [${REG_MIRRORS}]
           }
           EOF
      - name: Reload Docker
        shell: bash
        id: reload-docker
        run: |
           sudo cat /etc/docker/daemon.json
           sudo systemctl daemon-reload && sudo systemctl restart docker
      - name: Configure buildx
        uses: docker/setup-buildx-action@v3
        with:
          # AE: This appeared to have an issue for a user, so it's being set to
          # false for now.
          cache-binary: false
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = [${{ inputs.buildkitRegistryMirror }}]
              http = ${{ inputs.buildkitRegistryHTTP }}
              insecure = ${{ inputs.buildkitRegistryInsecure }}
            [registry.${{ inputs.buildkitRegistryMirror }}]
              http = ${{ inputs.buildkitRegistryHTTP }}
              insecure = ${{ inputs.buildkitRegistryInsecure }}
